### ISSUE TITLE
Dynamical attr_accessible attributes

### ISSUE THREAD

**Issue by HendrikRoth** [Leadformance/hstore_translate#18]
Instead of defining each several language for attr_accessible

``` ruby
class Product < ActiveRecord::Base
  attr_accessible :name_en, :name_de, :name_fr
  translates :name
end
```

it would be nice to set only one central attribute.

``` ruby
class Product < ActiveRecord::Base
  attr_accessible :name_translations
  translates :name
end
```

Is there a way to change this behavior?

**Comment by isness** [comment]
> I18n.available_locales.each { |locale| attr_accessible "name_#{locale}" }
Is there a nice way to do this in Rails 4? I understand I have to list all fields as strong params, but I've been unable to find any nice looking solution if there are many locales and a lot of translated fields.
