### ISSUE TITLE
Deprecation warning in Rails 5

### ISSUE THREAD

**Issue by dsmalko** [Leadformance/hstore_translate#56]
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super
(called from translates at ../gems/hstore_translate-bf7541fbc1c2/lib/hstore_translate/translates.rb:30

**Comment by bublik** [comment]
+1

**Comment by jaybloke** [comment]
+1

**Comment by openscript** [comment]
I've created a fork of this project, which is fully compatible with Rails 5. Check it out here:
https://github.com/openscript/awesome_hstore_translate
